version: 2.1

orbs:
  node: circleci/node@5.1.0

# Define the jobs we want to run for this project
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run test
          command: npm run test
      - run:
          name: Run build
          command: ls -la
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run build
          command: npm run build
     - persist_to_workspace:
          root: ~/project
          paths:
            - .

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
      - build
