version: 2.1

orbs:
  node: circleci/node@5.1.0
  eb: circleci/aws-elastic-beanstalk@1.0.0

# Define the jobs we want to run for this project
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run test
          command: npm run test
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run build
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install AWS CLI
          command: |
            curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Install pip
          command: |
            curl -O https://bootstrap.pypa.io/get-pip.py
            python get-pip.py --user
            pip install --user awsebcli
            export PATH=$HOME/.local/bin:$PATH
      - run:
          name: Install virtualenv
          command: |
            pip install --user virtualenv
      - run:
          name: Set AWS credentials
          command: |
            aws configure set aws_access_key_id AKIAQN4PD4RKFHHDHRS3
            aws configure set aws_secret_access_key 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
      - run:
          name: Set AWS default region
          command: aws configure set region eu-central-1
      - run:
          name: Install Elastic Beanstalk CLI
          command: |
            wget https://github.com/aws/aws-elastic-beanstalk-cli-setup/archive/master.tar.gz -O aws-elastic-beanstalk-cli-setup.tar.gz
            tar -xzf aws-elastic-beanstalk-cli-setup.tar.gz
            cd aws-elastic-beanstalk-cli-setup-master/scripts
            pip install --upgrade pip
            pip install awsebcli
      - run:
          name: Run Elastic Beanstalk CLI Installer
          command: python aws-elastic-beanstalk-cli-setup-master/scripts/ebcli_installer.py
      - run:
          name: Run deployoment
          command: npm run deploy

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
      - build
      - deploy:
          requires:
            - test
            - build
