version: 2.1

orbs:
  node: circleci/node@5.1.0
  eb: circleci/aws-elastic-beanstalk@1.0.0

# Define the jobs we want to run for this project
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run test
          command: npm run test
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run build
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Elastic Beanstalk CLI
          command: npm install -g awsebcli
      - run:
          name: Deploy to AWS EB
          command: npm run deploy

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test
      - build
      - deploy:
          requires:
            - test
            - build
