version: 2.1
orbs: circleci/node@5.1.0
jobs:
  build:
    docker:
      - image: 'cimg/base:2022.05'
    steps:
      - node/install
      - checkout
      - run:
        name: hello
        command: |
          echo "hello-world"
