version: 2.1

orbs:
  node: circleci/node@5.1.0
  # eb: circleci/aws-elastic-beanstalk@1.0.0

# Define the jobs we want to run for this project
jobs:
  test_build_deploy_dev:
    executor: node/default # defines the execution env --> Standard-Node.js env
    environment: # sets the environment variable to dev
      ENV: dev
    steps:
      - checkout # copies the code from the git repo to build env
      - node/install-packages: # uses the node Orb to install the Node.js-Pakete, using npm as package manager
          pkg-manager: npm
      - run:
          name: Display ENV
          command: |
            echo "Content of ENV: $ENV"
      - run:
          name: Run test on dev # runs the npm test script ("npx tsc && db-migrate up && jasmine")
          command: npm run test
      - run:
          name: Run build on dev # runs the npm build script ("rm -rf dist && npx tsc && cp -r package.json database.json migrations sslcerts assets dist/",)
          command: npm run build
      - run:
          name: Install pip # installs pip package management for Python; required to install AWS Elastic Beanstalk CLI

          command: |
            curl -O https://bootstrap.pypa.io/get-pip.py
            python get-pip.py --user
            pip install --user awsebcli
            export PATH=$HOME/.local/bin:$PATH
      - run:
          name: Install virtualenv # installs virtualenv, a tool to create an isolated Python env
          command: |
            pip install --user virtualenv
      - run:
          name: Install Elastic Beanstalk CLI # installs EB CLI
          command: |
            wget https://github.com/aws/aws-elastic-beanstalk-cli-setup/archive/master.tar.gz -O aws-elastic-beanstalk-cli-setup.tar.gz
            tar -xzf aws-elastic-beanstalk-cli-setup.tar.gz
            cd aws-elastic-beanstalk-cli-setup-master/scripts
            pip install --upgrade pip
            pip install awsebcli
      - run:
          name: Run Elastic Beanstalk CLI Installer # runs the Python install script
          command: python aws-elastic-beanstalk-cli-setup-master/scripts/ebcli_installer.py
      - run:
          name: Checking EB env # Due to deploy error
          command: |
            eb list
            eb status
      - run:
          name: Run deploy on dev # runs the npm deploy script ("chmod +x ./bin/deploy.sh && ./bin/deploy.sh")
          command: npm run deploy # runs "eb deploy"

  test_build_deploy_prod:
    executor: node/default
    environment:
      ENV: prod
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Display ENV
          command: |
            echo "Content of ENV: $ENV"
      - run:
          name: Run test on PROD
          command: npm run test
      - run:
          name: Run build on PROD
          command: npm run build
      - run:
          name: Install pip
          command: |
            curl -O https://bootstrap.pypa.io/get-pip.py
            python get-pip.py --user
            pip install --user awsebcli
            export PATH=$HOME/.local/bin:$PATH
      - run:
          name: Install virtualenv
          command: |
            pip install --user virtualenv
      - run:
          name: Install Elastic Beanstalk CLI
          command: |
            wget https://github.com/aws/aws-elastic-beanstalk-cli-setup/archive/master.tar.gz -O aws-elastic-beanstalk-cli-setup.tar.gz
            tar -xzf aws-elastic-beanstalk-cli-setup.tar.gz
            cd aws-elastic-beanstalk-cli-setup-master/scripts
            pip install --upgrade pip
            pip install awsebcli
      - run:
          name: Run Elastic Beanstalk CLI Installer
          command: python aws-elastic-beanstalk-cli-setup-master/scripts/ebcli_installer.py
      - run:
          name: Run deploy on PROD
          command: npm run deploy

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test_build_deploy_dev:
          filters:
            branches:
              only: dev
      - test_build_deploy_prod:
          filters:
            branches:
              only: main
