version: 2.1

orbs:
  node: circleci/node@5.1.0

# Define the jobs we want to run for this project
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run test
          command: npm run test
      - run:
          name: Run build
          command: ls -la
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run:
          name: Echo Test Message
          command: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
