version: 2.1

orbs:
  node: circleci/node@5.1.0

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - node/install
      - checkout
      - run:
        name: Install API
        command: |
          npm run install
      - run:
        name: Build API
        command: |
          npm run build
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
